os:
  - linux
dist: focal
language: node_js
node_js:
  - 14.2.0
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: 'EPgcsjerbKEWduJFgRmW5mx4hCliGyw1IVokb6oMo/MqDEn0ZrAHBj/cz4Qp7XoUj1arRg80g4JJcJADyS2KkLwZwzdKsS662fe9Yzgxi6FVIq6dy8fNstuNjrw+ANT+Low1A5yoHntOKi4hZ9awu+q6kSITScUTjPqoeU+NjIMB1dX+6OskoRJlCmg0U/Y68tDdmXxXwnnq8jXwmVhbFs4vN4cipef5X6uDJXlQaBmkwb+4CeA1aMs4Xzvfm9cD72pwuj1Qx3N/8UYyHIi/6KHiJdmb/Jf66diXecbwhLV4elbPaNjAp+aineuypaInXLgVtRU6elQe1v//5m39jOmuwL9Ik1GKAsRhsi0tG2z34xA2LXbKGbC37eTbxnQ2OdWPVehFh3AZAWmUHa4QCRzQTHBKkR7Cis3Nr+tSbpr5RfmU3OImAecSZ3SvZ6KkWXwUWFz3J7wKGjDsKbmgl0suPaAPWLyNu525jf5I7D1NTRuG+12o0eBKSNnVhmWkO5z1MOo2ZMiIdWNsatogoHUvGJy6iE0HubX2i9LeF+zVae5vqXycFnDjiEthRBGjg+fAVlDuvUmDiY4n8LRQR3+cxqAVhIFrmWMHUM1v/axh9kmQZaHCUJe2U7k3W/VfX7cCqPEhc1sIvPAh9ZxTbVkfY2WkCQnL2hMGQ2Mjcb0='
